spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/business_banya
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: validate

application:
  telegram:
    token: 7987083088:AAGsUg3Y9tU05Q0GDCBCn06PTAYl446bMnE