spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/business_banya
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    feign: DEBUG
    ru.snptech.businessbanyabot: DEBUG

application:
  host: http://localhost:8080
  base-url: api/v1

  telegram:
    token: 7987083088:AAGsUg3Y9tU05Q0GDCBCn06PTAYl446bMnE
  integration:
    bank:
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmYmZmNzYyMzYxMzIwNDNlODVmMjUyNGFkNTk1MjRiOCJ9.gZtq3vwZWNiLUO5kC8i1lKyuLOX5u1Y94HOHC1jiIBqtHF8i2ZJn36YjR-VMILCLHy7e05aqEU_5hbQ9lFNsK4F3OYKwTadMvQB2hhB_bE2osgu8IbLDsKHLIgNxWes4Jf3KmIN_xwsA2CrvB2-9vCY-EgtkLTZBQgWBe0hNRVFl1ts9ayzBf-lIo2dW8rrzhDGLsU2hZEL3O9WAmKD3hWEPdxLUkCF0D7Ya2lQ7I7ltQ743QaHmdS-uPMz4wooZl0CmtaxtCpqvwjQlfiaPG8vF-Gz2aD4f-igMEWTNPPqVttDgtNzAcM8DmXSpoPfLOnz3TizUPhwjRMQR5GsEVY-yJFfkXqa-HykITAk84cB8DQb7yPNHEquIEcuZqvyrSBa1LYYL90POmWJg1kaM8JcJCBA_pJKwiLWmEDOsdd3cHyRbbXH_RfWUudY8TClvA8mHRnZyMnwIKCZgts8DY9Nj4AdGlXaJEFZegDH8g8ETiIKpLqBOyvPWgdTYFB12
      url: https://enter.tochka.com/sandbox/v2
      merchant-id: MA0004166381
      account-id: 40802810420000153009/044525104
      client-id: fbff76236132043e85f2524ad59524b8
      api-version: v1.0
      qr-code-settings:
        image-settings:
          size: 400
          media-type: image/png
        ttl-in-minutes: 120
        currency: RUB
        money-amount: 100
      webhook:
        url: ${application.host}/${application.base-url}/integration/bank/webhook

