CREATE TABLE IF NOT EXISTS survey
(
    id                   bigserial PRIMARY KEY,
    chat_id              bigint      NOT NULL REFERENCES telegram_user (chat_id),
    fio                  text,
    social_media         text,
    date_of_birth        date,
    city                 text,
    years_of_experience  text,
    withdrawals          text,
    business_description text,
    family_status        text,
    children_count       text,
    sport_interests      text,
    beliefs              text,
    music_singers        text,
    crucial_words        text,
    films                text,
    strengths            text,
    victories            text,
    defeats              text,
    teachers             text,
    goals                text,
    active_side          text,
    passive_side         text,
    referrer             text,
    status               text        NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    delivered_at         timestamptz
);